Slider2
front-end-by-rimantas/37-grupe-portfolio-docland pull request #50
Opened 2022-07-04 06:27 UTC by ZbignevZ

CSS slider 2 Course Benefit. Without JS. Not responsible

2022-07-04 09:57 UTC, saulius334 requested changes
Reikia responsive

2022-07-04 11:33 UTC, ZbignevZ commented
CSS man magija. Padariau responsive, please check it ar gerai

2022-07-04 16:06 UTC, VilmaPetruskeviciene reviewed
Man tai rodo taip responsiva:
![Untitled](https://user-images.githubusercontent.com/105633730/177189630-4363d421-e0ac-427a-a305-efc562050849.png)

2022-07-05 07:58 UTC, saulius334 approved these changes

2022-07-07 05:12 UTC, Domasbab approved these changes

2022-07-07 05:12 UTC, merged