Karusele2 fix CSS,Btn and bacground
front-end-by-rimantas/37-grupe-portfolio-docland pull request #74
Opened 2022-07-08 08:05 UTC by ZbignevZ

Pakeistas karuseles stilius, responsive tarpai

2022-07-08 08:40 UTC, VilmaPetruskeviciene approved these changes

2022-07-08 09:28 UTC, zasweted requested changes
![image](https://user-images.githubusercontent.com/105633847/177961922-7425490a-adc1-489a-8e97-b041649ef668.png)
![image](https://user-images.githubusercontent.com/105633847/177961994-328cedc6-8375-4b01-afdf-d25ceb10d8a3.png)
Spalvos, dydis, sriftas, antrastes pozicija

2022-07-08 11:51 UTC, Kalis1990 approved these changes
ok

2022-07-08 12:00 UTC, Kalis1990 requested changes
reiketu pakeisti didzius ir teksto spalva

2022-07-11 06:14 UTC, VilmaPetruskeviciene submitted a review, later dismissed

2022-07-11 10:17 UTC, ZbignevZ commented
Nuimtas background color, pataisytas box width; title position left, content color is gray.

2022-07-12 05:59 UTC, zasweted requested changes
![image](https://user-images.githubusercontent.com/105633847/178419240-d04f8b16-7c0e-414f-84db-b7a2a7136f4e.png)

Gal tas korteles padariti platesnes ?

2022-07-12 06:50 UTC, ZbignevZ commented
koki bracha ziurit ???

2022-07-12 06:51 UTC, closed without merging